# This is a basic workflow to help you get started with Actions

name: Three

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
 
    steps:
      - name: Fred
        run: echo "{markdown content}" >> $GITHUB_STEP_SUMMARY

  job2:
    needs: [job1]
    uses: markharrison/actions1/.github/workflows/four.yml@main
    with:
      param1: "param x"
      param2: "param y"
    secrets:
      registry_username: "username"
      registry_password: "password"
          
